apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 00-openshift-machineconfig-worker-psi
spec:
  kernelArguments:
    - psi=1
