apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- Namespace.yaml
- OperatorGroup.yaml
- Subscription.yaml
- MetalLB/metallb.yaml
- L2Advertisement/coe-lab.yaml
- IPAddressPool/coe-lab.yaml
