apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-kube-descheduler-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/tux1980/descheduler.git
    targetRevision: HEAD
    path: operator/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
