apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-add-evict-annotation
  namespace: openshift-gitops 
data:
  add-annotation.py: |
    #!/usr/bin/env python3
    import sys
    import yaml

    for file_path in sys.argv[1:]:
        with open(file_path, 'r') as f:
            manifests = list(yaml.safe_load_all(f))
            
        for manifest in manifests:
            if manifest and manifest.get('kind') == 'VirtualMachine':
                template_metadata = manifest.get('spec', {}).get('template', {}).get('metadata', {})
                labels = template_metadata.get('labels', {})
                if labels.get('descheduler') == 'LongLifecycle':
                    annotations = template_metadata.get('annotations', {})
                    if 'descheduler.alpha.kubernetes.io/evict' not in annotations:
                        annotations['descheduler.alpha.kubernetes.io/evict'] = 'true'
                        template_metadata['annotations'] = annotations
        
        with open(file_path, 'w') as f:
            yaml.dump_all(manifests, f, sort_keys=False)

  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: add-evict-annotation
    spec:
      generate:
        command: ["python3", "add-annotation.py"]
        args: ["./"]
      preserveFileMode: true
