apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-openshift-machineconfig-worker-psi
spec:
  kernelArguments:
    - psi=1
    - systemd.unified_cgroup_hierarchy=1
