apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: descheduler-operator-group
  namespace: openshift-kube-descheduler-operator
spec:
  targetNamespaces:
    - openshift-kube-descheduler-operator
